stages:
    - test

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - .npm
        - cache/Cypress
        - node_modules

cypress-e2e:
    image: cypress/base:10
    stage: test
    before_script:
        - npm install
    script:
        - cypress:run
    # artifacts:
    #     expire_in: 1 week
    #     when: always
    #     paths:
    #         - cypress/screenshots
    #         - cypress/videos

cypress-e2e-chrome:
    image: cypress/browsers:chrome67
    stage: test
    before_script:
        - npm install
    script:
        - cypress:run:browse
    # artifacts:
    #     expire_in: 1 week
    #     when: always
    #     paths:
    #         - cypress/screenshots
    #         - cypress/videos
