version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.15.3
        working_directory: ~/repo

        steps:
            - checkout
            - restore_cache:
                  key: v1-npm-deps-{{ checksum "package.json" }}
            - run: yarn
            - save_cache:
                  key: v1-npm-deps-{{ checksum "package.json" }}
                  paths:
                      - ./node_modules
            - run: yarn build

    cypress/run:
        docker:
        - image: cypress/base:8
            environment:
            ## this enables colors in the output
            TERM: xterm
        working_directory: ~/app
        steps:
        - checkout
        - restore_cache:
            keys:
                - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
                - v1-deps-{{ .Branch }}
                - v1-deps
        - run:
            name: Install Dependencies
            command: yarn install --frozen-lockfile
        - save_cache:
            key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            paths:
                - ~/.cache  ## cache both yarn and Cypress!
        - run: $(yarn bin)/cypress run --record --key <record_key>

    deploy:
        docker:
            - image: buildpack-deps:trusty
        steps:
            - checkout
            - run:
                  name: Deploy Master to Heroku
                  command: |
                      git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
    version: 2
    build-test-and-deploy:
        jobs:
            - build
            - cypress/run:
                record: true
                requires:
                    - build
            - deploy:
                  requires:
                      - cypress/run
                  filters:
                      branches:
                          only: develop
