version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:10.15.3
        working_directory: ~/repo

        steps:
            - checkout
            - restore_cache:
                  key: v1-npm-deps-{{ checksum "package.json" }}
            - run: yarn
            - save_cache:
                  key: v1-npm-deps-{{ checksum "package.json" }}
                  paths:
                      - node_modules
            # - run: yarn cypress:run
            # - run: yarn cypress:run:browse
            - run: yarn build
    deploy:
        docker:
            - image: buildpack-deps:trusty
        steps:
            - checkout
            - run:
                  name: Deploy Master to Heroku
                  command: |
                      git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
    version: 2.1
    build-deploy:
        jobs:
            - build
            - deploy:
                  requires:
                      - build
                  filters:
                      branches:
                          only: develop
