version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.15.3
        working_directory: ~/repo

        steps:
            - checkout
            - restore_cache:
                  key: v1-npm-deps-{{ checksum "package.json" }}
            - run: yarn
            - save_cache:
                  key: v1-npm-deps-{{ checksum "package.json" }}
                  paths:
                      - ./node_modules
            - run: yarn build

    cypress/run:
        docker:
            - image: cypress/base:10
        parallelism: 1
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - cache-{{ .Branch }}-{{ checksum "package.json" }}
            - run:
                command: unset NODE_OPTIONS
            - run:
                  command: NODE_OPTIONS=--max_old_space_size=4096 yarn cypress verify
            - save_cache:
                  key: cache-{{ .Branch }}-{{ checksum "package.json" }}
                  paths:
                      - ~/.npm
                      - ~/.cache
            - persist_to_workspace:
                  root: ~/
                  paths:
                      - project
                      - .cache/Cypress
            - attach_workspace:
                  at: ~/
            - run:
                  name: Run Cypress tests
                  command: 'yarn cypress run'

    deploy:
        docker:
            - image: buildpack-deps:trusty
        steps:
            - checkout
            - run:
                  name: Deploy Master to Heroku
                  command: |
                      git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
    version: 2
    build-test-and-deploy:
        jobs:
            - cypress/run
            # - build
            # - cypress/run:
                    # record: true
            #       requires:
            #           - build
            # - deploy:
            #       requires:
            #           - cypress/run
            #       filters:
            #           branches:
            #               only: develop
